package Vistas.Consultas;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultasClientes.java
 *
 * Created on 15-abr-2013, 8:33:48
 */


import DB.Generator.CustomDefaultTableModel;
import DB.Conector;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrador
 */
public class CONSULTA_VENDEDORES extends javax.swing.JInternalFrame {
 
    private String ConsultaSQL;
    
    public CONSULTA_VENDEDORES() {
        initComponents();
        txtcodigo.setEnabled(false);
        ResultSet resultado = null;
        /*
        Connection cn = null;
        try{
            cn = Conector.conexion();
            Statement st = cn.createStatement();
            resultado = st.executeQuery("SHOW TABLES LIKE 'VISTA_VENDEDORES'");
            int rs;
            if ( ! resultado.next() )
                rs = st.executeUpdate("CREATE VIEW VISTA_VENDEDORES AS  SELECT * FROM VENDEDORES ");
            
            ConsultaSQL = "SELECT * FROM VISTA_VENDEDORES";
            CargarlistaVendedores();
        
        }catch ( SQLException excepcionSql ){
            excepcionSql.printStackTrace();
        } // fin de catch
        */
    }
    void CargarlistaVendedores()          
    {
        CustomDefaultTableModel modelo= new CustomDefaultTableModel();
        String []Titulos = {"CODIGO","NOMBRES","TELEFONO","EMAIL"};
        modelo.setColumnIdentifiers(Titulos);
        this.tbvendedores.setModel(modelo);
        /*
        try {          
        
            String []registros= new String[4];
           
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);
            while(rs.next())
            {
                registros[0]=rs.getString("VenCod");
                registros[1]=rs.getString("VenNom");
                registros[2]=rs.getString("VenTel");  
                registros[3]=rs.getString("VenEmail");  
                modelo.addRow(registros);
                                
            }
            tbvendedores.setModel(modelo);
            txtcant.setText(""+tbvendedores.getRowCount());
        } catch (SQLException ex) {
            Logger.getLogger(CONSULTA_VENDEDORES.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btncodigo = new javax.swing.JRadioButton();
        btntodo = new javax.swing.JRadioButton();
        txtcodigo = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnnombre = new javax.swing.JRadioButton();
        txtnombre = new javax.swing.JTextField();
        btntelefono = new javax.swing.JRadioButton();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbvendedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONSULTA DE VENDEDORES");

        buttonGroup1.add(btncodigo);
        btncodigo.setText("Buscar Vendedor por codigo:");
        btncodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncodigoActionPerformed(evt);
            }
        });

        buttonGroup1.add(btntodo);
        btntodo.setText("Mostrar todos los vendedores");
        btntodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntodoActionPerformed(evt);
            }
        });

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnnombre);
        btnnombre.setText("Buscar Vendedor por nombre:");
        btnnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnombreActionPerformed(evt);
            }
        });

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(btntelefono);
        btntelefono.setText("Buscar Vendedor por telefono:");
        btntelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntelefonoActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btntodo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btntelefono)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnnombre)
                                    .addComponent(btncodigo))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnbuscar)
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncodigo)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnnombre)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntodo)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tbvendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbvendedores);

        jLabel1.setText("Cantidad de Registros");

        txtcant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcant.setEnabled(false);

        jButton2.setText("Generar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
// TODO add your handling code here:
   
   String codigo = txtcodigo.getText();
   String nombre = txtnombre.getText();
   String telefono = txtTelefono.getText();
  
   if(btncodigo.isSelected()==true)
   {
       ConsultaSQL="SELECT * FROM VISTA_VENDEDORES WHERE VenCod = "+codigo;
       CargarlistaVendedores();     
   }
   if(btnnombre.isSelected()==true)
   {
       ConsultaSQL="SELECT * FROM VISTA_VENDEDORES WHERE VenNom= '"+nombre+"'";
       CargarlistaVendedores();              
   }
   if(btntelefono.isSelected()==true)
   {     
       ConsultaSQL="SELECT * FROM VISTA_VENDEDORES WHERE VenTel="+telefono;
       CargarlistaVendedores();    
   }
   
   if(btntodo.isSelected()==true)
   {
       ConsultaSQL="SELECT * FROM VISTA_VENDEDORES";
       CargarlistaVendedores();
   }
   
}//GEN-LAST:event_btnbuscarActionPerformed

private void btncodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncodigoActionPerformed
// TODO add your handling code here:
    if(btncodigo.isSelected()==true)
    {       
        txtcodigo.setEnabled(true);
        txtcodigo.requestFocus();
    }
}//GEN-LAST:event_btncodigoActionPerformed

private void btntodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntodoActionPerformed
// TODO add your handling code here:
    CargarlistaVendedores();
    txtcodigo.setText("");
    txtcodigo.setEnabled(false);
}//GEN-LAST:event_btntodoActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
//    List lista = new ArrayList();
//    for(int i=0;i<tbclientes.getRowCount();i++)
//    {
//        listaclientes clientes= new listaclientes(tbclientes.getValueAt(i, 0).toString(), 
//                tbclientes.getValueAt(i, 1).toString(), tbclientes.getValueAt(i, 2).toString(), tbclientes.getValueAt(i, 4).toString(), tbclientes.getValueAt(i, 6).toString());
//        lista.add(clientes);
//    }
//        try {
//            JasperReport reporte= (JasperReport) JRLoader.loadObject("reportescliente.jasper");
//            Map parametro = new HashMap();
//            parametro.put("genero", cbogenero.getSelectedItem());
//            
//            JasperPrint jprint= JasperFillManager.fillReport(reporte, parametro,new JRBeanCollectionDataSource(lista));
//            JasperViewer.viewReport(jprint,false);
//        } catch (JRException ex) {
//            Logger.getLogger(CONSULTA_CLIENTES.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    
    
}//GEN-LAST:event_jButton2ActionPerformed


    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void btnnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnombreActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btntelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntelefonoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JRadioButton btncodigo;
    private javax.swing.JRadioButton btnnombre;
    private javax.swing.JRadioButton btntelefono;
    private javax.swing.JRadioButton btntodo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbvendedores;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables


}
