package Vistas;


import OAD.PG_L13001_Mantenim_de_Art;
import OAD.PG_L13004_Mantenim_de_Suc;
import OAD.PG_L13005_Mantenim_de_Cli;
import DB.Generator.CustomDefaultTableModel;
import DB.Generator.GeneradorCodigos;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MARIO HUAYPUNA
 */
public class BUSCAR_ARTICULO_COT extends javax.swing.JFrame {

    /**
     * Creates new form BUSCAR_ARTICULO_COT
     */
    private final PG_L13001_Mantenim_de_Art PREPARAR_DECLARACION;
    Object [][] dbArticulos;
    CustomDefaultTableModel modelo;
    private int filaSeleccionada;
    private GeneradorCodigos nuevo;
    Border BorderCajaNoEditable;
    Border BorderCajaEditable;
    
    CustomDefaultTableModel TABLA_COTIZACION_DET;
    
    
    public BUSCAR_ARTICULO_COT( CustomDefaultTableModel CURRENT ) {
        initComponents();
        this.setLocationRelativeTo(null);
        PREPARAR_DECLARACION = new PG_L13001_Mantenim_de_Art();
        BorderCajaEditable = this.CajaNomCli.getBorder();
                
        dbArticulos = PREPARAR_DECLARACION.obtenerTodasLosArticulosQueEsten("A");
        String[] columNames = {"CODIGO","DESCRIPCION","PREC. UNIT","SUCURSAL","EMPRESA"}; 
        modelo = new CustomDefaultTableModel(dbArticulos, columNames);
        TABLA_MOSTRAR_CIAS.setModel(modelo);
        
        TABLA_COTIZACION_DET = CURRENT;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        CajaNomCli = new javax.swing.JTextField();
        BotonGuardarCli = new javax.swing.JButton();
        BotonActualizarCli = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLA_MOSTRAR_CIAS = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel8.setText("BUSCAR ARTICULO");

        CajaNomCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaNomCliMouseClicked(evt);
            }
        });

        BotonGuardarCli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonGuardarCli.setText("MOSTRAR TODO");
        BotonGuardarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarCliActionPerformed(evt);
            }
        });

        BotonActualizarCli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonActualizarCli.setText("SELECCIONAR ARTICULO");
        BotonActualizarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarCliActionPerformed(evt);
            }
        });

        TABLA_MOSTRAR_CIAS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TABLA_MOSTRAR_CIAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TABLA_MOSTRAR_CIAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_MOSTRAR_CIASMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TABLA_MOSTRAR_CIAS);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("ATRAS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(CajaNomCli)
                        .addGap(18, 18, 18)
                        .addComponent(BotonGuardarCli)
                        .addGap(18, 18, 18)
                        .addComponent(BotonActualizarCli))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(CajaNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonGuardarCli)
                    .addComponent(BotonActualizarCli))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaNomCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaNomCliMouseClicked
        // TODO add your handling code here:
        CajaNomCli.setBorder(BorderCajaEditable);
    }//GEN-LAST:event_CajaNomCliMouseClicked

    private void BotonGuardarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarCliActionPerformed

    }//GEN-LAST:event_BotonGuardarCliActionPerformed

    private void BotonActualizarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarCliActionPerformed
        String [] ArticuloAlista = new String[5];
        int fila = TABLA_MOSTRAR_CIAS.getSelectedRow();
        if(fila >= 0){
            ArticuloAlista[0] = TABLA_MOSTRAR_CIAS.getValueAt(fila, 0).toString();
            ArticuloAlista[1] = TABLA_MOSTRAR_CIAS.getValueAt(fila, 1).toString();
            ArticuloAlista[2] = TABLA_MOSTRAR_CIAS.getValueAt(fila, 2).toString();
            ArticuloAlista[3] = "";
            ArticuloAlista[4] = "";
            dispose();        
            TABLA_COTIZACION_DET.addRow(ArticuloAlista);           
        }
        else{
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
        }
    }//GEN-LAST:event_BotonActualizarCliActionPerformed

    private void TABLA_MOSTRAR_CIASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_MOSTRAR_CIASMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TABLA_MOSTRAR_CIASMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();        // BOTON ATRAS
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarCli;
    private javax.swing.JButton BotonGuardarCli;
    private javax.swing.JTextField CajaNomCli;
    private javax.swing.JTable TABLA_MOSTRAR_CIAS;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
