package Vistas;

import DB.Generator.CodeGenerate;
import OAD.PG_L13002_Mantenim_de_Cia;
import OAD.PG_L13003_Mantenim_de_Ven;
import OAD.PG_L13004_Mantenim_de_Suc;
import OAD.PG_L13005_Mantenim_de_Cli;
import OAD.PG_L16001_Cotizacion_Cab;
import OAD.PG_L16002_Cotizacion_Det;
import DB.Generator.CustomDefaultTableModel;
import DB.Generator.Entities;
import DB.Generator.FileGeneradorCodigos;
import DB.Generator.GeneradorCodigos;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author Jose Vargas
 */
public class COTIZACION extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddInforme
     */
    private final PG_L16001_Cotizacion_Cab DECLARACION_CABECERA;
    private final PG_L16002_Cotizacion_Det DECLARACION_DETALLE;
    //Object [][] dbCotizacionDet;
    CustomDefaultTableModel modelo;
    private int filaSeleccionada;
    Border BorderCajaNoEditable;
    Border BorderCajaEditable;
    String [] articuloParaCotizar;
    
    Object [][] dbSucursalesCOT;
    
    private BUSCAR_CIA_COT busquedaCia;
   
    private final PG_L13004_Mantenim_de_Suc EXTRACTOR_SUCS;
    
    private final PG_L13003_Mantenim_de_Ven EXTRACTOR_VENDEDORES;
    Object [][] dbVendedores;
    
    public COTIZACION() {
        
        initComponents();
        DECLARACION_CABECERA = new PG_L16001_Cotizacion_Cab();
        DECLARACION_DETALLE = new PG_L16002_Cotizacion_Det();
        BorderCajaNoEditable = this.CajaCodigoCia.getBorder();
                      
        //dbCotizacionDet = PREPARAR_DECLARACION.obtenerTodasLosClientesQueEsten("A");
        modelo = new CustomDefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PREC. UNIT");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("SUBTOTAL");
       
        TABLA_MOSTRAR_CIAS.setModel(modelo);
        dbSucursalesCOT = null;
        this.LabelRUC.setText("RUC: ");
        //this.ComboBoxNombreSuc.addItem("-- select item --");
        
        EXTRACTOR_SUCS = new PG_L13004_Mantenim_de_Suc();
        
        // obtenemos los Vendedores para poder mostrar al usuario al momento de introducir la CiaCod
        EXTRACTOR_VENDEDORES = new PG_L13003_Mantenim_de_Ven();
        dbVendedores = EXTRACTOR_VENDEDORES.obtenerTodasLosVendedoresQueEsten("A");
        
        for( int i=0;i<dbVendedores.length; i++)
           ComboBoxNombreVen.addItem(dbVendedores[i][1] );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        bGroup_Preg_01 = new javax.swing.ButtonGroup();
        bGroup_Preg_02 = new javax.swing.ButtonGroup();
        bGroup_Preg_03 = new javax.swing.ButtonGroup();
        bGroup_Preg_04 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLA_MOSTRAR_CIAS = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        LabelRUC = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CajaCotCabNum = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CajaCodigoCia = new javax.swing.JTextField();
        BotonGuardarCli1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CajaCodigoVen = new javax.swing.JTextField();
        ComboBoxNombreVen = new javax.swing.JComboBox();
        ComboBoxNombreSuc = new javax.swing.JComboBox();
        CajaCodigoSuc = new javax.swing.JTextField();
        CajaNombreCia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        CajaNombreCli = new javax.swing.JTextField();
        CajaCodigoCli = new javax.swing.JTextField();
        BotonGuardarCli2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CajaDireccionCli = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CajaFecha = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        CajaFormaPago = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CajaPlazoEntreg = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        CajaGarantia = new javax.swing.JTextField();
        ComboBoxNombreCias2 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        BotonGuardarCli4 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        BotonActualizarCli = new javax.swing.JButton();
        BotonGuardarCotizacion = new javax.swing.JButton();
        BotonActualizarCli1 = new javax.swing.JButton();
        BotonGuardarCli6 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jMenuItem1.setText("Asignar cantidad");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Calcular subtotal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("COTIZACION");

        TABLA_MOSTRAR_CIAS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TABLA_MOSTRAR_CIAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TABLA_MOSTRAR_CIAS.setComponentPopupMenu(jPopupMenu1);
        TABLA_MOSTRAR_CIAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_MOSTRAR_CIASMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TABLA_MOSTRAR_CIAS);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelRUC.setText("RUC 10046495581");

        jLabel17.setText("COD");

        CajaCotCabNum.setEditable(false);
        CajaCotCabNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaCotCabNumMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel27.setText("COTIZACION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(60, 60, 60))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CajaCotCabNum)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CajaCotCabNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CajaCodigoCia.setEditable(false);
        CajaCodigoCia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaCodigoCiaMouseClicked(evt);
            }
        });
        CajaCodigoCia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCodigoCiaActionPerformed(evt);
            }
        });

        BotonGuardarCli1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonGuardarCli1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/24x24/search.png"))); // NOI18N
        BotonGuardarCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarCli1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setText("COMPAÑIA");

        jLabel11.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel11.setText("SUCURSAL");

        jLabel9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel9.setText("VENDEDOR");

        CajaCodigoVen.setEditable(false);
        CajaCodigoVen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaCodigoVenMouseClicked(evt);
            }
        });
        CajaCodigoVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCodigoVenActionPerformed(evt);
            }
        });

        ComboBoxNombreVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNombreVenActionPerformed(evt);
            }
        });

        ComboBoxNombreSuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxNombreSucMouseClicked(evt);
            }
        });
        ComboBoxNombreSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNombreSucActionPerformed(evt);
            }
        });

        CajaCodigoSuc.setEditable(false);
        CajaCodigoSuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaCodigoSucMouseClicked(evt);
            }
        });
        CajaCodigoSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCodigoSucActionPerformed(evt);
            }
        });

        CajaNombreCia.setEditable(false);
        CajaNombreCia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaNombreCiaMouseClicked(evt);
            }
        });
        CajaNombreCia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaNombreCiaActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addGap(22, 22, 22))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CajaCodigoSuc, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(CajaCodigoVen)
                    .addComponent(CajaCodigoCia))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBoxNombreSuc, javax.swing.GroupLayout.Alignment.TRAILING, 0, 230, Short.MAX_VALUE)
                    .addComponent(ComboBoxNombreVen, javax.swing.GroupLayout.Alignment.TRAILING, 0, 230, Short.MAX_VALUE)
                    .addComponent(CajaNombreCia))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonGuardarCli1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CajaCodigoCia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaNombreCia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajaCodigoSuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(ComboBoxNombreSuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CajaCodigoVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComboBoxNombreVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BotonGuardarCli1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CajaNombreCli.setEditable(false);
        CajaNombreCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaNombreCliMouseClicked(evt);
            }
        });
        CajaNombreCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaNombreCliActionPerformed(evt);
            }
        });

        CajaCodigoCli.setEditable(false);
        CajaCodigoCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaCodigoCliMouseClicked(evt);
            }
        });

        BotonGuardarCli2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonGuardarCli2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/24x24/search.png"))); // NOI18N
        BotonGuardarCli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarCli2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel12.setText("FECHA");

        jLabel13.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel13.setText("SEÑOR ( A )");

        jLabel14.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel14.setText("DIRECCION");

        CajaDireccionCli.setEditable(false);
        CajaDireccionCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaDireccionCliMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel16.setText("COD CLI");

        CajaFecha.setEditable(false);
        CajaFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaFechaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CajaNombreCli)
                    .addComponent(CajaDireccionCli, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(BotonGuardarCli2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CajaCodigoCli)
                    .addComponent(CajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel12)
                            .addComponent(CajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajaCodigoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addComponent(BotonGuardarCli2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(CajaNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajaDireccionCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CajaFormaPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaFormaPagoMouseClicked(evt);
            }
        });
        CajaFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaFormaPagoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel23.setText("FORMA DE PAGO");

        jLabel24.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel24.setText("PLAZO DE ENTREGA");

        CajaPlazoEntreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaPlazoEntregMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel25.setText("GARANTIA");

        CajaGarantia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaGarantiaMouseClicked(evt);
            }
        });

        ComboBoxNombreCias2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNombreCias2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CajaGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CajaPlazoEntreg, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(CajaFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxNombreCias2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(CajaFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxNombreCias2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(CajaPlazoEntreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(CajaGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel22.setText("ARTICULO");

        BotonGuardarCli4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonGuardarCli4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/24x24/search.png"))); // NOI18N
        BotonGuardarCli4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarCli4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(67, 67, 67))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonGuardarCli4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonGuardarCli4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BotonActualizarCli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonActualizarCli.setText("REALIZAR CALCULO");
        BotonActualizarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarCliActionPerformed(evt);
            }
        });

        BotonGuardarCotizacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonGuardarCotizacion.setText("REALIZAR COTIZACION");
        BotonGuardarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarCotizacionActionPerformed(evt);
            }
        });

        BotonActualizarCli1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonActualizarCli1.setText("ELIMINAR");
        BotonActualizarCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarCli1ActionPerformed(evt);
            }
        });

        BotonGuardarCli6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonGuardarCli6.setText("SALIR");
        BotonGuardarCli6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarCli6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonGuardarCli6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonGuardarCotizacion)
                    .addComponent(BotonActualizarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonActualizarCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BotonActualizarCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonGuardarCotizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonActualizarCli1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonGuardarCli6)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaCodigoCiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaCodigoCiaMouseClicked
        // TODO add your handling code here:
        CajaCodigoCia.setBorder(BorderCajaNoEditable);

        CajaCodigoCia.setText( String.valueOf( CodeGenerate.getCode(Entities.COTIZACION_CAB) )  );
    }//GEN-LAST:event_CajaCodigoCiaMouseClicked

    private void CajaCodigoCiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCodigoCiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCodigoCiaActionPerformed

    private void TABLA_MOSTRAR_CIASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_MOSTRAR_CIASMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TABLA_MOSTRAR_CIASMouseClicked

    private void BotonActualizarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarCliActionPerformed

    }//GEN-LAST:event_BotonActualizarCliActionPerformed

    private void BotonGuardarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarCotizacionActionPerformed
        FileGeneradorCodigos file = new FileGeneradorCodigos();

        DECLARACION_CABECERA.agregarCotizacionCab( Integer.parseInt(CajaCotCabNum.getText()),
                CajaFecha.getText(), CajaGarantia.getText(), CajaPlazoEntreg.getText(),
                        CajaFormaPago.getText(),"A" ,
                                Integer.parseInt( CajaCodigoCli.getText() ), Integer.parseInt( CajaCodigoVen.getText() ),
                                Integer.parseInt( CajaCodigoSuc.getText() ), Integer.parseInt( CajaCodigoCia.getText() ) );
        
        guardarCotizacionesDet( Integer.parseInt(CajaCotCabNum.getText()) );
        
        modelo = new CustomDefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PREC. UNIT");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("SUBTOTAL");
       
        TABLA_MOSTRAR_CIAS.setModel(modelo);
        limpiar();
    }//GEN-LAST:event_BotonGuardarCotizacionActionPerformed
  
   
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        int fila = TABLA_MOSTRAR_CIAS.getSelectedRow();
        String entrada;
        if(fila >= 0){
            do{
            entrada = JOptionPane.showInputDialog ( null,
                    "Introduzca un valor",
                    "Mi programa en Java",
                    JOptionPane.QUESTION_MESSAGE );
            }while( !checkNum( entrada ) );
             modelo.setValueAt( entrada, fila, 3 );
        }else
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int fila = TABLA_MOSTRAR_CIAS.getSelectedRow();
        if(fila >= 0){
            if( TABLA_MOSTRAR_CIAS.getValueAt(fila, 3).toString().equals("") ){
                JOptionPane.showMessageDialog(null, "No se asigno una cantidad");
                return;
            }        
            double PRECIO_UNIT = Double.parseDouble( TABLA_MOSTRAR_CIAS.getValueAt(fila, 2).toString() );
            int cantidad = Integer.parseInt( TABLA_MOSTRAR_CIAS.getValueAt(fila, 3).toString() );
            double subtotal = PRECIO_UNIT*cantidad;
            modelo.setValueAt( String.valueOf(subtotal), fila, 4 );
        }
        else{
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void BotonGuardarCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarCli1ActionPerformed
        // TODO add your handling code here:   
        busquedaCia = new BUSCAR_CIA_COT( CajaCodigoCia, CajaNombreCia, LabelRUC, ComboBoxNombreSuc );
        busquedaCia.setResizable(false);
        busquedaCia.setVisible(true);
    }//GEN-LAST:event_BotonGuardarCli1ActionPerformed

    private void CajaCotCabNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaCotCabNumMouseClicked
        // TODO add your handling code here:
        CajaCotCabNum.setBorder(BorderCajaNoEditable);

        CajaCotCabNum.setText( String.valueOf( CodeGenerate.getCode(Entities.COTIZACION_CAB) )  );
    }//GEN-LAST:event_CajaCotCabNumMouseClicked

    private void CajaCodigoCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaCodigoCliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCodigoCliMouseClicked

    private void BotonGuardarCli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarCli2ActionPerformed
        // TODO add your handling code here:
        ///BUSCAR CLIENTE 
        
        BUSCAR_CLIENTE_COT busqueda = new BUSCAR_CLIENTE_COT( CajaCodigoCli, CajaNombreCli, CajaDireccionCli );
        busqueda.setResizable(false);
        busqueda.setVisible(true);
        
    }//GEN-LAST:event_BotonGuardarCli2ActionPerformed

    private void CajaFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaFechaMouseClicked
        // TODO add your handling code here:
        CajaFecha.setText( fechaactual() );
    }//GEN-LAST:event_CajaFechaMouseClicked

    private void CajaDireccionCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaDireccionCliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaDireccionCliMouseClicked

    private void CajaNombreCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaNombreCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaNombreCliActionPerformed

    private void CajaNombreCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaNombreCliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaNombreCliMouseClicked

    private void CajaCodigoVenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaCodigoVenMouseClicked
        // TODO add your handling code here:
        CajaCodigoVen.setBorder(BorderCajaNoEditable);
    }//GEN-LAST:event_CajaCodigoVenMouseClicked

    private void CajaCodigoVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCodigoVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCodigoVenActionPerformed

    private void ComboBoxNombreVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNombreVenActionPerformed
        if( ComboBoxNombreVen.getSelectedIndex() == -1 )
            return;
        int registerRow = ComboBoxNombreVen.getSelectedIndex();
        CajaCodigoVen.setText( dbVendedores[registerRow][0].toString() );
    }//GEN-LAST:event_ComboBoxNombreVenActionPerformed

    private void ComboBoxNombreSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNombreSucActionPerformed
        // TODO add your handling code here:
        if( ComboBoxNombreSuc.getSelectedIndex() == -1 )
            return;
        int registerRow = ComboBoxNombreSuc.getSelectedIndex();
            //System.out.print(" dbSucursales recontra vacio ");
        System.out.println(" - >  " + registerRow );
        CajaCodigoSuc.setText( dbSucursalesCOT[registerRow][0].toString() );
    }//GEN-LAST:event_ComboBoxNombreSucActionPerformed

    private void CajaCodigoSucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaCodigoSucMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCodigoSucMouseClicked

    private void CajaCodigoSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCodigoSucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCodigoSucActionPerformed

    private void CajaFormaPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaFormaPagoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaFormaPagoMouseClicked

    private void CajaFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaFormaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaFormaPagoActionPerformed

    private void CajaPlazoEntregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaPlazoEntregMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaPlazoEntregMouseClicked

    private void CajaGarantiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaGarantiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaGarantiaMouseClicked

    private void ComboBoxNombreCias2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNombreCias2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxNombreCias2ActionPerformed

    private void BotonGuardarCli4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarCli4ActionPerformed
        // TODO add your handling code here:
        BUSCAR_ARTICULO_COT busqueda = new BUSCAR_ARTICULO_COT( modelo );
        busqueda.setResizable(false);
        busqueda.setVisible(true);
    }//GEN-LAST:event_BotonGuardarCli4ActionPerformed

    private void BotonActualizarCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarCli1ActionPerformed
        // TODO add your handling code here:
        int fila = TABLA_MOSTRAR_CIAS.getSelectedRow();
        if(fila >= 0){
            //PREPARAR_DECLARACION.EliminarArticulo(Integer.parseInt( TABLA_MOSTRAR_CIAS.getValueAt(fila, 0).toString() ) );
            modelo.removeRow(fila);
        }
        else{
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
        }
        
    }//GEN-LAST:event_BotonActualizarCli1ActionPerformed

    private void BotonGuardarCli6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarCli6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarCli6ActionPerformed

    private void CajaNombreCiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaNombreCiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaNombreCiaMouseClicked

    private void CajaNombreCiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaNombreCiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaNombreCiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if( CajaCodigoCia.getText() == "" ){
            JOptionPane.showMessageDialog(null, "No ha introducido codigo de Cia en el campo.");
            return;
        }
        
        dbSucursalesCOT = null;
        dbSucursalesCOT = EXTRACTOR_SUCS.obtenerSucursalesDeCiaActivas("A", this.CajaCodigoCia.getText());
            ComboBoxNombreSuc.removeAllItems();
            
            for( int i=0;i<dbSucursalesCOT.length; i++)
                ComboBoxNombreSuc.addItem( dbSucursalesCOT[i][1] ); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBoxNombreSucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxNombreSucMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboBoxNombreSucMouseClicked
 /*
    *Funciones de validacion de elementos
    *
    */
    public void setFilaSeleccionada( int row ){
        filaSeleccionada = row;
    }
    public int getFilaSeleccionada(){
        return filaSeleccionada;
    }
    
    
    public boolean DatosValidos( ){
        boolean flag1, flag2,flag3;
        flag1 = flag2 = flag3 = true;
        if( !checkNum(CajaCodigoCia.getText()) ){ 
            CajaCodigoCia.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            flag1 = false;
        }
        return ( flag1 && flag2 && flag3);
    }
    
    public boolean checkAlpha(String cadena) {
	boolean respuesta = false;
	if ((cadena).matches("([a-z]|[A-Z]|\\s)+")) {
            respuesta = true;
	}
        return respuesta;	
    }
    public boolean checkAlphayNumber(String cadena) {
	boolean respuesta = false;
	if ((cadena).matches("([a-z]|[A-Z]|[0-9]|\\s|\\.|\\-)+")) {
            respuesta = true;
	}
	return respuesta;
    }
    public boolean checkNum(String str){ 
        boolean respuesta = false; 
        if ((str).matches("([0-9])+")) { 
            respuesta = true; 
        } 
        return respuesta; 
    }
    
    public static String fechaactual(){
        Date fecha= new Date();
        SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    
    private void guardarCotizacionesDet( int cotCabNum){
        boolean resultado=true;
        for( int i=0; i < TABLA_MOSTRAR_CIAS.getRowCount(); i++){      
            int codigoArt = Integer.parseInt( TABLA_MOSTRAR_CIAS.getValueAt(i, 0).toString() );
            int cantidad = Integer.parseInt( TABLA_MOSTRAR_CIAS.getValueAt(i, 3).toString() );
            
            DECLARACION_DETALLE.AgregarCotizacionDet(cantidad, "A", codigoArt, cotCabNum);      
        }       
    }
       
    private void limpiar(){
        CajaCotCabNum.setText("");
        CajaFecha.setText("");
        CajaGarantia.setText("");
        CajaPlazoEntreg.setText("");
        CajaFormaPago.setText("");
        CajaCodigoCli.setText("");
        CajaCodigoVen.setText("");
        CajaCodigoSuc.setText("");
        CajaCodigoCia.setText("");  
        CajaNombreCli.setText("");
        CajaDireccionCli.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarCli;
    private javax.swing.JButton BotonActualizarCli1;
    private javax.swing.JButton BotonGuardarCli1;
    private javax.swing.JButton BotonGuardarCli2;
    private javax.swing.JButton BotonGuardarCli4;
    private javax.swing.JButton BotonGuardarCli6;
    private javax.swing.JButton BotonGuardarCotizacion;
    private javax.swing.JTextField CajaCodigoCia;
    private javax.swing.JTextField CajaCodigoCli;
    private javax.swing.JTextField CajaCodigoSuc;
    private javax.swing.JTextField CajaCodigoVen;
    private javax.swing.JTextField CajaCotCabNum;
    private javax.swing.JTextField CajaDireccionCli;
    private javax.swing.JTextField CajaFecha;
    private javax.swing.JTextField CajaFormaPago;
    private javax.swing.JTextField CajaGarantia;
    private javax.swing.JTextField CajaNombreCia;
    private javax.swing.JTextField CajaNombreCli;
    private javax.swing.JTextField CajaPlazoEntreg;
    private javax.swing.JComboBox ComboBoxNombreCias2;
    private javax.swing.JComboBox ComboBoxNombreSuc;
    private javax.swing.JComboBox ComboBoxNombreVen;
    private javax.swing.JLabel LabelRUC;
    private javax.swing.JTable TABLA_MOSTRAR_CIAS;
    private javax.swing.ButtonGroup bGroup_Preg_01;
    private javax.swing.ButtonGroup bGroup_Preg_02;
    private javax.swing.ButtonGroup bGroup_Preg_03;
    private javax.swing.ButtonGroup bGroup_Preg_04;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
