package Vistas;

import DB.Generator.CodeGenerate;
import OAD.PG_L13001_Mantenim_de_Art;
import OAD.PG_L13002_Mantenim_de_Cia;
import OAD.PG_L13004_Mantenim_de_Suc;
import OAD.PG_L13005_Mantenim_de_Cli;
import DB.Generator.CustomDefaultTableModel;
import DB.Generator.Entities;
import DB.Generator.FileGeneradorCodigos;
import DB.Generator.GeneradorCodigos;
import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Vargas
 */
public class TABLA_ARTICULOS extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddInforme
     */
    private final PG_L13001_Mantenim_de_Art PREPARAR_DECLARACION;
    Object [][] dbArticulos;
    CustomDefaultTableModel modelo;
    private int filaSeleccionada;
    private GeneradorCodigos nuevo;
    Border BorderCajaNoEditable;
    Border BorderCajaEditable;
    
    private final PG_L13002_Mantenim_de_Cia EXTRACTOR_CIAS;
    private Object [][] dbCias;
    
    private final PG_L13004_Mantenim_de_Suc EXTRACTOR_SUCS;
    private Object [][] dbSucursales;
    
    public TABLA_ARTICULOS() {
        
        initComponents();
        PREPARAR_DECLARACION = new PG_L13001_Mantenim_de_Art();
        BorderCajaNoEditable = this.CajaCodigoArt.getBorder();
        BorderCajaEditable = this.CajaDescripcionArt.getBorder();
                
        dbArticulos = PREPARAR_DECLARACION.obtenerTodasLosArticulosQueEsten("A");
        String[] columNames = {"CODIGO","DESCRIPCION","PREC. UNIT","SUCURSAL","EMPRESA"}; 
        modelo = new CustomDefaultTableModel(dbArticulos, columNames);
        TABLA_MOSTRAR_CIAS.setModel(modelo);
        // obtenemos las CIAS para poder mostrar al usuario al momento de introducir la CiaCod
        EXTRACTOR_CIAS = new PG_L13002_Mantenim_de_Cia();
        dbCias = EXTRACTOR_CIAS.obtenerTodasLasCiasQueEsten("A");
        
        for( int i=0;i<dbCias.length; i++)
           ComboBoxNombreCias.addItem( dbCias[i][1] );
        
        // obtenemos las SUCURSALES para poder mostrar al usuario al momento de introducir la SucCodç
        EXTRACTOR_SUCS = new PG_L13004_Mantenim_de_Suc();
        //dbSucursales = EXTRACTOR_SUCS.obtenerSucursalesDeCiaActivas("A", Integer.parseInt( dbCias[0][0].toString() ) );
        
        //for( int i=0;i<dbSucursales.length; i++)
        //   ComboBoxNombreSuc.addItem( dbSucursales[i][1] );
    }

    void limpiar(){
        CajaCodigoArt.setText("");
        CajaPrecUnit.setText("");
        CajaDescripcionArt.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CajaCodigoArt = new javax.swing.JTextField();
        CajaDescripcionArt = new javax.swing.JTextField();
        CajaPrecUnit = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLA_MOSTRAR_CIAS = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        BotonActualizarArt = new javax.swing.JButton();
        BotonGuardarArt = new javax.swing.JButton();
        CajaCiaCodigo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ComboBoxNombreCias = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        CajaSucCodigo = new javax.swing.JTextField();
        ComboBoxNombreSuc = new javax.swing.JComboBox();

        jMenuItem1.setText("MODIFICAR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("ELIMINAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ARTICULOS");

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setText("CÓDIGO");

        jLabel8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel8.setText("DESCRIPCION");

        jLabel9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel9.setText("PRECIO UNIT.");

        CajaCodigoArt.setEditable(false);
        CajaCodigoArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaCodigoArtMouseClicked(evt);
            }
        });
        CajaCodigoArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCodigoArtActionPerformed(evt);
            }
        });

        CajaDescripcionArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaDescripcionArtMouseClicked(evt);
            }
        });

        CajaPrecUnit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaPrecUnitMouseClicked(evt);
            }
        });

        TABLA_MOSTRAR_CIAS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TABLA_MOSTRAR_CIAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TABLA_MOSTRAR_CIAS.setComponentPopupMenu(jPopupMenu1);
        TABLA_MOSTRAR_CIAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_MOSTRAR_CIASMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TABLA_MOSTRAR_CIAS);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("ATRAS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        BotonActualizarArt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonActualizarArt.setText("ACTUALIZAR");
        BotonActualizarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarArtActionPerformed(evt);
            }
        });

        BotonGuardarArt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonGuardarArt.setText("GUARDAR");
        BotonGuardarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarArtActionPerformed(evt);
            }
        });

        CajaCiaCodigo.setEditable(false);
        CajaCiaCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaCiaCodigoMouseClicked(evt);
            }
        });
        CajaCiaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCiaCodigoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel12.setText("EMPRESA");

        ComboBoxNombreCias.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ComboBoxNombreCias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxNombreCiasItemStateChanged(evt);
            }
        });
        ComboBoxNombreCias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNombreCiasActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel13.setText("SUCURSAL");

        CajaSucCodigo.setEditable(false);
        CajaSucCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaSucCodigoMouseClicked(evt);
            }
        });
        CajaSucCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaSucCodigoActionPerformed(evt);
            }
        });

        ComboBoxNombreSuc.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ComboBoxNombreSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNombreSucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajaCiaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaSucCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxNombreSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotonGuardarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonActualizarArt)))
                            .addComponent(ComboBoxNombreCias, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CajaCodigoArt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaDescripcionArt, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                            .addComponent(CajaPrecUnit))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonGuardarArt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonActualizarArt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7)
                            .addComponent(CajaCodigoArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(CajaDescripcionArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajaPrecUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxNombreCias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxNombreSuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(CajaSucCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajaCiaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaCodigoArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaCodigoArtMouseClicked
        // TODO add your handling code here:
        CajaCodigoArt.setBorder(BorderCajaNoEditable);
        //FileGeneradorCodigos file = new FileGeneradorCodigos();
        //file.leer();
        //nuevo = file.getGenerador();
        CajaCodigoArt.setText( String.valueOf( CodeGenerate.getCode(Entities.ARTICULOS) )  );
    }//GEN-LAST:event_CajaCodigoArtMouseClicked

    private void CajaCodigoArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCodigoArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCodigoArtActionPerformed

    private void CajaDescripcionArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaDescripcionArtMouseClicked
        // TODO add your handling code here:
        CajaDescripcionArt.setBorder(BorderCajaEditable);
    }//GEN-LAST:event_CajaDescripcionArtMouseClicked

    private void CajaPrecUnitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaPrecUnitMouseClicked
        // TODO add your handling code here:
        CajaPrecUnit.setBorder(BorderCajaEditable);
    }//GEN-LAST:event_CajaPrecUnitMouseClicked

    private void TABLA_MOSTRAR_CIASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_MOSTRAR_CIASMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TABLA_MOSTRAR_CIASMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();        // BOTON ATRAS

    }//GEN-LAST:event_jButton5ActionPerformed

    private void BotonActualizarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarArtActionPerformed
        if( !DatosValidos() )
        return;
        // TODO add your handling code here:
        PREPARAR_DECLARACION.ActualizarArticulo( Integer.parseInt( this.CajaCodigoArt.getText()), 
                this.CajaDescripcionArt.getText(),
                Double.parseDouble( this.CajaPrecUnit.getText() ),
                "A",
                Integer.parseInt( this.CajaSucCodigo.getText()),
                Integer.parseInt( this.CajaCiaCodigo.getText()));
        
        modelo.setValueAt(CajaDescripcionArt.getText(), getFilaSeleccionada(), 1 );
        modelo.setValueAt(CajaPrecUnit.getText(), getFilaSeleccionada(), 2 );
        modelo.setValueAt(CajaSucCodigo.getText(), getFilaSeleccionada(), 3 );
        modelo.setValueAt(CajaCiaCodigo.getText(), getFilaSeleccionada(), 4 );
        
        limpiar();
        CajaCodigoArt.setEnabled(true);
        BotonGuardarArt.setEnabled(true);
        BotonActualizarArt.setEnabled(false);
    }//GEN-LAST:event_BotonActualizarArtActionPerformed

    private void BotonGuardarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarArtActionPerformed
        if( !DatosValidos() )
        return;
        FileGeneradorCodigos file = new FileGeneradorCodigos();
        file.escribir(nuevo);

        PREPARAR_DECLARACION.agregarArticulo(Integer.parseInt( this.CajaCodigoArt.getText()),
            this.CajaDescripcionArt.getText(),
            Double.parseDouble( this.CajaPrecUnit.getText() ),
            "A",
            Integer.parseInt( this.CajaSucCodigo.getText()),
            Integer.parseInt( this.CajaCiaCodigo.getText()));

        String [] datos = new String[5];
        datos[0] = CajaCodigoArt.getText();
        datos[1] = CajaDescripcionArt.getText();
        datos[2] = CajaPrecUnit.getText();
        datos[3] = CajaSucCodigo.getText();
        datos[4] = CajaCiaCodigo.getText();

        limpiar();
        modelo.addRow(datos);

    }//GEN-LAST:event_BotonGuardarArtActionPerformed

    private void CajaCiaCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaCiaCodigoMouseClicked
        // TODO add your handling code here:
        CajaCiaCodigo.setBorder(BorderCajaNoEditable);
    }//GEN-LAST:event_CajaCiaCodigoMouseClicked

    private void CajaCiaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCiaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCiaCodigoActionPerformed

    private void ComboBoxNombreCiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNombreCiasActionPerformed
        // TODO add your handling code here:
        if( ComboBoxNombreCias.getSelectedIndex() == -1 )
            return;
        int registerRow = ComboBoxNombreCias.getSelectedIndex();
        String codCia = dbCias[registerRow][0].toString();
        CajaCiaCodigo.setText( codCia );
        
        // PARTE DE COMBOBOX DE SUCURSALes
            PG_L13004_Mantenim_de_Suc SUCURSALES = new PG_L13004_Mantenim_de_Suc();
            dbSucursales = SUCURSALES.obtenerSucursalesDeCiaActivas("A", codCia  );
            
            ComboBoxNombreSuc.removeAllItems();
            
            for( int i=0;i<dbSucursales.length; i++)
               ComboBoxNombreSuc.addItem( dbSucursales[i][1] );
             
        
    }//GEN-LAST:event_ComboBoxNombreCiasActionPerformed

    private void CajaSucCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaSucCodigoMouseClicked
        // TODO add your handling code here:
        CajaSucCodigo.setBorder(BorderCajaNoEditable);
    }//GEN-LAST:event_CajaSucCodigoMouseClicked

    private void CajaSucCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaSucCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaSucCodigoActionPerformed

    private void ComboBoxNombreSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNombreSucActionPerformed
        // TODO add your handling code here:
        if( ComboBoxNombreSuc.getSelectedIndex() == -1 )
            return;
        int registerRow = ComboBoxNombreSuc.getSelectedIndex();
        CajaSucCodigo.setText( dbSucursales[registerRow][0].toString() );
    }//GEN-LAST:event_ComboBoxNombreSucActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int fila = TABLA_MOSTRAR_CIAS.getSelectedRow();
        if(fila >= 0){
            CajaCodigoArt.setText(TABLA_MOSTRAR_CIAS.getValueAt(fila, 0).toString());
            CajaDescripcionArt.setText(TABLA_MOSTRAR_CIAS.getValueAt(fila, 1).toString());
            CajaPrecUnit.setText(TABLA_MOSTRAR_CIAS.getValueAt(fila, 2).toString());
            CajaCiaCodigo.setText(TABLA_MOSTRAR_CIAS.getValueAt(fila, 4).toString());
            CajaSucCodigo.setText(TABLA_MOSTRAR_CIAS.getValueAt(fila, 3).toString());
            CajaCodigoArt.setEnabled(false);
            BotonGuardarArt.setEnabled(false);
            BotonActualizarArt.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
        }
        setFilaSeleccionada( fila );
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int fila = TABLA_MOSTRAR_CIAS.getSelectedRow();
        if(fila >= 0){
            PREPARAR_DECLARACION.EliminarArticulo(Integer.parseInt( TABLA_MOSTRAR_CIAS.getValueAt(fila, 0).toString() ) );
        }
        else{
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
        }
        modelo.removeRow(fila);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ComboBoxNombreCiasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxNombreCiasItemStateChanged
        // TODO add your handling code here:
        if( evt.getStateChange() == ItemEvent.SELECTED ){
            
        }
    }//GEN-LAST:event_ComboBoxNombreCiasItemStateChanged
 /*
    *Funciones de validacion de elementos
    *
    */
    public void setFilaSeleccionada( int row ){
        filaSeleccionada = row;
    }
    public int getFilaSeleccionada(){
        return filaSeleccionada;
    }
    
    
    public boolean DatosValidos( ){
        boolean flag1, flag2,flag3, flag4, flag5;
        flag1 = flag2 = flag3 = flag4 = flag5 = true;
        if( !checkNum(CajaCodigoArt.getText()) ){ 
            CajaCodigoArt.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            flag1 = false;
        }
        if( !checkAlphayNumber(CajaDescripcionArt.getText()) ){
            CajaDescripcionArt.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            flag2 =  false;
        }
        if( !checkNumDecimal(CajaPrecUnit.getText())  ){
            CajaPrecUnit.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            flag3 = false;    
        }
        if( !checkNum(CajaCiaCodigo.getText()) ){ 
            CajaCiaCodigo.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            flag4 = false;
        }
        if( !checkNum(CajaSucCodigo.getText()) ){ 
            CajaSucCodigo.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            flag5 = false;
        }
        return ( flag1 && flag2 && flag3 && flag4 && flag5 );
    }
    
    public boolean checkAlpha(String cadena) {
	boolean respuesta = false;
	if ((cadena).matches("([a-z]|[A-Z]|\\s)+")) {
            respuesta = true;
	}
        return respuesta;	
    }
    public boolean checkAlphayNumber(String cadena) {
	boolean respuesta = false;
	if ((cadena).matches("([a-z]|[A-Z]|[0-9]|\\s|\\.|\\-)+")) {
            respuesta = true;
	}
	return respuesta;
    }
    public boolean checkNum(String str){ 
        boolean respuesta = false; 
        if ((str).matches("([0-9])+")) { 
            respuesta = true; 
        } 
        return respuesta; 
    }
    public boolean checkNumDecimal( String str ){
        boolean respuesta = false; 
        if ((str).matches("([0-9]|\\.)+")) { 
            respuesta = true; 
        } 
        return respuesta;
    }
    
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarArt;
    private javax.swing.JButton BotonGuardarArt;
    private javax.swing.JTextField CajaCiaCodigo;
    private javax.swing.JTextField CajaCodigoArt;
    private javax.swing.JTextField CajaDescripcionArt;
    private javax.swing.JTextField CajaPrecUnit;
    private javax.swing.JTextField CajaSucCodigo;
    private javax.swing.JComboBox ComboBoxNombreCias;
    private javax.swing.JComboBox ComboBoxNombreSuc;
    private javax.swing.JTable TABLA_MOSTRAR_CIAS;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
